USE [sqldb-ods-dev]
GO
/****** Object:  StoredProcedure [StgADM].[SrcDimProductJurisdictionClassCode]    Script Date: 27.10.2022 12:28:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [StgADM].[SrcDimProductJurisdictionClassCode] @CutOffDateFrom VARCHAR(100)
AS
DECLARE @DateFrom DATETIME = CAST(@CutOffDateFrom AS DATETIME)

SELECT *
FROM (
	SELECT *
		,ROW_NUMBER() OVER (PARTITION BY SourceSystemCode,SourceCode ORDER BY SourceCode) AS rn
	FROM (
		SELECT
			--ProductJurisdictionSK AUTO GENERATED
			--RowCreatedBySK		  Populated in ADF
			--,RowCreatedDtm		  Populated in ADF
			--,RowLastUpdatedBySK	  Populated in ADF
			--,RowLastUpdatedDtm	  Populated in ADF
			src.SourceSystemCode AS SourceSystemCode
			,prn.SourceCode  AS SourceCode				-- doesn't exist in ODS
			,TRY_CAST('1900-01-01' AS DATETIME) AS RowEffectiveFromDatetime
			,TRY_CAST('3000-01-01' AS DATETIME) AS RowEffectiveToDatetime
			,'0' AS GovernanceValidationInd		-- generated by default not loaded from the ODS - Default value '0'
			,'0' AS StandardValueInd			-- generated by default not loaded from the ODS - Default value '0'
			,'NoStdVal' AS StandardValueCkCode	-- System generated by default - Default value '8(NoStdVal)'
			,tss.StateCode  AS JurisdictionCkCode
			,'STATE'       AS   JurisdictionCode
			,tlb.LineofBusinessCode 
			,'ASLOB'  AS   ProductCategoryLevelCode
			,CASE WHEN  tcc.ClassCodeSK IS NOT NULL THEN   'ISO CLASS CODE'
			  ELSE 'ISO STATE CODE'END  AS  ProductJurisdictionClassCodeTypeName
			,tcc.ClassCode AS   ProductJurisdictionClassCode
			,tcc.ClassCodeName AS   ProductJurisdictionClassCodeName
			,null AS ProductJurisdictionClassCodeDefn
			,null AS Tfscode

FROM Policy.RatingPlan prn
JOIN Typelist.SourceSystem src ON src.SourceSystemSK=prn.SourceSystemSK
LEFT JOIN Typelist.ClassCode  tcc ON prn.ClassCodeSK=tcc.ClassCodeSK
LEFT JOIN Policy.PolicyGeography pgy ON pgy.PolicyGeographySK=prn.PolicyGeographySK
LEFT JOIN Typelist.State tss ON tss.StateSK=pgy.StateSK
LEFT JOIN Typelist.LineofBusiness tlb ON tlb.LineofBusinessSK=prn.PolicyLineofBusinessSK
	) tmp
	) tbl
	WHERE tbl.rn = 1
GO
