USE [sqldb-ods-dev]
GO
/****** Object:  Table [dbo].[DIMCalendarDay_fromDM]    Script Date: 28.10.2022 11:09:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIMCalendarDay_fromDM](
	[CalendarDayDate] [date] NOT NULL,
	[RowCreatedBySK] [int] NULL,
	[RowLastUpdatedBySK] [int] NULL,
	[RowCreatedDtm] [datetime] NOT NULL,
	[RowLastUpdatedDtm] [datetime] NOT NULL,
	[SourceSystemSK] [int] NOT NULL,
	[SourceCode] [varchar](300) NULL,
	[CalendarDate] [date] NOT NULL,
	[CalendarLabelMMDDYYYYAbrv] [varchar](25) NULL,
	[CalendarYearNbr] [int] NULL,
	[CalendarQuarterNbr] [tinyint] NULL,
	[CalendarQuarterDayNbr] [tinyint] NULL,
	[CalendarHalfYearLabelYYYYQAbrv] [int] NULL,
	[CalendarHalfYearLabelNbr] [tinyint] NULL,
	[CalendarHalfYearLabelName] [varchar](13) NULL,
	[CalendarHalfYearLabelStartDateAbrv] [varchar](25) NULL,
	[CalendarHalfYearLabelEndDateAbrv] [varchar](25) NULL,
	[CalendarYearQuarterLabelYYYYQAbrv] [int] NULL,
	[CalendarYearQuarterName] [varchar](25) NULL,
	[CalendarYearMonthLabelYYYYMMAbrv] [int] NULL,
	[CalendarYearMonthName] [varchar](25) NULL,
	[CalendarYearWeekLabelYYYYWWAbrv] [int] NULL,
	[CalendarYearDayNbr] [smallint] NULL,
	[CalendarYearWeekNbr] [tinyint] NULL,
	[CalendarMonthNbr] [tinyint] NULL,
	[CalendarMonthName] [varchar](25) NULL,
	[CalendarQuarterStartDateLabelAbrv] [varchar](25) NULL,
	[CalendarQuarterEndDateLabelAbrv] [varchar](25) NULL,
	[CalendarMonthStartDateLabelAbrv] [varchar](25) NULL,
	[CalendarMonthEndDateLabelAbrv] [varchar](25) NULL,
	[CalendarMonthDayNbr] [tinyint] NULL,
	[CalendarMonSunWeekDayNbr] [int] NULL,
	[CalendarWeekDayName] [varchar](25) NULL,
	[CalendarWeekDayTypeName] [varchar](25) NULL,
	[HolidayInd] [tinyint] NULL,
	[CalendarMonSunWeekStartDateLabelAbrv] [varchar](25) NULL,
	[CalendarMonSunWeekEndDateLabelAbrv] [varchar](25) NULL,
	[CalendarDaysInWeekNbr] [tinyint] NULL,
	[CalendarDaysInYearNbr] [smallint] NULL,
	[CalendarDaysInMonthNbr] [tinyint] NULL,
	[CalendarWeeksInMonthNbr] [tinyint] NULL,
	[CalendarWeeksInYearNbr] [tinyint] NULL,
	[CalendarDayDesc] [varchar](50) NULL,
	[FirstDayOfWeekDate] [date] NULL,
	[LastDayOfWeekDate] [date] NULL,
	[FirstDayOfMonthDate] [date] NULL,
	[LastDayOfMonthDate] [date] NULL,
	[FirstDayOfQuarterDate] [date] NULL,
	[LastDayOfQuarterDate] [date] NULL,
	[FirstDayOfTrimesterDate] [date] NULL,
	[LastDayOfTrimesterDate] [date] NULL,
	[FirstDayHalfYearDate] [date] NULL,
	[LastDayHalfYearDate] [date] NULL,
	[FirstDayOfCurrentYearDate] [date] NULL,
	[LastDayOfCurrentYearDate] [date] NULL,
	[FirstDayOfPreviousYearDate] [date] NULL,
	[LastDayOfPreviousYearDate] [date] NULL
) ON [PRIMARY]
GO
