USE [master]
GO
/****** Object:  Database [sqldb-ods-dev]    Script Date: 28.10.2022 15:04:14 ******/
CREATE DATABASE [sqldb-ods-dev]
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [sqldb-ods-dev].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [sqldb-ods-dev] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [sqldb-ods-dev] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [sqldb-ods-dev] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [sqldb-ods-dev] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [sqldb-ods-dev] SET ARITHABORT OFF 
GO
ALTER DATABASE [sqldb-ods-dev] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [sqldb-ods-dev] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [sqldb-ods-dev] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [sqldb-ods-dev] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [sqldb-ods-dev] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [sqldb-ods-dev] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [sqldb-ods-dev] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [sqldb-ods-dev] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [sqldb-ods-dev] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [sqldb-ods-dev] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [sqldb-ods-dev] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO
ALTER DATABASE [sqldb-ods-dev] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [sqldb-ods-dev] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [sqldb-ods-dev] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [sqldb-ods-dev] SET  MULTI_USER 
GO
ALTER DATABASE [sqldb-ods-dev] SET DB_CHAINING OFF 
GO
ALTER DATABASE [sqldb-ods-dev] SET ENCRYPTION ON
GO
ALTER DATABASE [sqldb-ods-dev] SET QUERY_STORE = ON
GO
ALTER DATABASE [sqldb-ods-dev] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 100, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO)
GO
USE [sqldb-ods-dev]
GO
ALTER DATABASE SCOPED CONFIGURATION SET ACCELERATED_PLAN_FORCING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ASYNC_STATS_UPDATE_WAIT_AT_LOW_PRIORITY = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ADAPTIVE_JOINS = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ON_ROWSTORE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET CE_FEEDBACK = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET DEFERRED_COMPILATION_TV = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET DW_COMPATIBILITY_LEVEL = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ELEVATE_ONLINE = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ELEVATE_RESUMABLE = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET EXEC_QUERY_STATS_FOR_SCALAR_FUNCTIONS = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET FORCE_SHOWPLAN_RUNTIME_PARAMETER_COLLECTION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET GLOBAL_TEMPORARY_TABLE_AUTO_DROP = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ISOLATE_SECURITY_POLICY_CARDINALITY = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LAST_QUERY_PLAN_STATS = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LIGHTWEIGHT_QUERY_PROFILING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 8;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MEMORY_GRANT_FEEDBACK_PERSISTENCE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET OPTIMIZE_FOR_AD_HOC_WORKLOADS = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SENSITIVE_PLAN_OPTIMIZATION = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PAUSED_RESUMABLE_INDEX_ABORT_DURATION_MINUTES = 1440;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ROW_MODE_MEMORY_GRANT_FEEDBACK = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET TSQL_SCALAR_UDF_INLINING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET VERBOSE_TRUNCATION_WARNINGS = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET XTP_PROCEDURE_EXECUTION_STATISTICS = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET XTP_QUERY_EXECUTION_STATISTICS = OFF;
GO
ALTER DATABASE [sqldb-ods-dev] SET  READ_WRITE 
GO
