USE [sqldb-ods-dev]
GO
/****** Object:  StoredProcedure [StgADM].[SrcDimProductCategory]    Script Date: 28.10.2022 13:37:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [StgADM].[SrcDimProductCategory] @CutOffDateFrom VARCHAR(100)
AS
DECLARE @DateFrom DATETIME = CAST(@CutOffDateFrom AS DATETIME)

--declare @DateFrom datetime='1900-01-01'
-- AnnualStatementLineOfBusiness with Coverage
SELECT SourceSystemCode
	,SourceCode
	,RowEffectiveFromDatetime
	,RowEffectiveToDatetime
	,GovernanceValidationInd
	,StandardValueInd
	,StandardValueCKcode
	,ParentProductCategoryCKcode
	,ProductCategoryTypeCKcode
	,ProductCategoryLevelCKcode
	,ProductCategoryCode
	,len(productcategorycode) AS length
	,LEFT(iif(ISNULL(ProductCategoryName, ProductCategoryCode) = '', ProductCategoryCode, ProductCategoryName), 75) AS ProductCategoryName
	,ProductCategoryFullyQualifiedName
	,isnull(ProductCategoryAbrv, ProductCategoryCode) AS ProductCategoryAbrv
	,ProductCategoryDefn
FROM (
	SELECT *
		,ROW_NUMBER() OVER (
			PARTITION BY ProductCategoryCode
			,SourceSystemCode
			,ProductCategoryLevelCKCode ORDER BY ProductCategoryCode
				,SourceSystemCode
				,ProductCategoryLevelCKCode DESC
			) AS rn
	FROM (
		SELECT
			--ProductCategorySK AUTO GENERATED
			--RowCreatedBySK		  Populated in ADF
			--,RowCreatedDtm		  Populated in ADF
			--,RowLastUpdatedBySK	  Populated in ADF
			--,RowLastUpdatedDtm	  Populated in ADF
			sty.SourceSystemCode AS SourceSystemCode
			,asl.AnnualStatementLineofBusinessCode AS SourceCode -- doesn't exist in ODS
			,CAST('1900-01-01' AS DATETIME) AS RowEffectiveFromDatetime
			,CAST('3000-01-01' AS DATETIME) AS RowEffectiveToDatetime
			,'0' AS GovernanceValidationInd -- generated by default not loaded from the ODS - Default value '0'
			,'0' AS StandardValueInd -- generated by default not loaded from the ODS - Default value '0'
			,'NoStdVal' AS StandardValueCKcode -- System generated by default - Default value '8(NoStdVal)'
			,NULL AS ParentProductCategoryCKcode --not available in ODS '(UnknownInSrc)' ?? should be null?
			,'C' AS ProductCategoryTypeCKcode									-- ref table ???
			,'ASLOB' AS ProductCategoryLevelCKcode -- ref table
			,asl.AnnualStatementLineofBusinessCode AS ProductCategoryCode
			,asl.AnnualStatementLineofBusinessName AS ProductCategoryName
			,asl.AnnualStatementLineofBusinessCode AS ProductCategoryFullyQualifiedName 
			,CAST(asl.AnnualStatementLineofBusinessCode AS VARCHAR(20)) AS ProductCategoryAbrv
			,NULL AS ProductCategoryDefn --not available in ODS
			----,cov.CoverageCode AS InternalCoverageCode-- ?coverage or subCoverage?
			--,cov.CoverageName AS InternalCoverageName-- ?coverage or subCoverage?
			--,ccl.CoverageClassCode AS StatClassCode
			--,pco.ClassCode AS ISOClassCode
		FROM Typelist.AnnualStatementLineOfBusiness asl
		--JOIN Typelist.Coverage cov ON cov.SourceSystemSK = asl.SourceSystemSK
		JOIN Typelist.SourceSystem sty ON sty.SourceSystemSK = asl.SourceSystemSK
		--JOIN Typelist.CoverageClass ccl ON ccl.IsStatCodeInd = 1
		--JOIN Policy.PolicyCoverage pco ON pco.SourceSystemSK = asl.SourceSystemSK 
		WHERE asl.ETLUpdateDateTime > @DateFrom
		
		UNION ALL
		
		--LineOfBusiness with Coverage
		SELECT
			--ProductCategorySK AUTO GENERATED
			--RowCreatedBySK		  Populated in ADF
			--,RowCreatedDtm		  Populated in ADF
			--,RowLastUpdatedBySK	  Populated in ADF
			--,RowLastUpdatedDtm	  Populated in ADF
			sty.SourceSystemCode AS SourceSystemCode
			,lob.LineofBusinessCode AS SourceCode -- doesn't exist in ODS
			,CAST('1900-01-01' AS DATETIME) AS RowEffectiveFromDatetime
			,CAST('3000-01-01' AS DATETIME) AS RowEffectiveToDatetime
			,0 AS GovernanceValidationInd -- generated by default not loaded from the ODS - Default value '0'
			,0 AS StandardValueInd -- generated by default not loaded from the ODS - Default value '0'
			,'NoStdVal' AS StandardValueSKcode -- System generated by default - Default value '8(NoStdVal)'
			,NULL AS ParentProductCategorySKcode --not available in ODS '(UnknownInSrc)' ??
			,'C' AS ProductCategoryTypeCKcode									-- ref table ???
			,'INSURTYP' AS ProductCategoryLevelCKcode -- ref table ???
			,lob.LineofBusinessCode AS ProductCategoryCode
			,lob.LineofBusinessName AS ProductCategoryName
			,lob.LineofBusinessCode AS ProductCategoryFullyQualifiedName --not available in ODS 
			,CAST(lob.LineofBusinessCode AS VARCHAR(20)) AS ProductCategoryAbrv
			,NULL AS ProductCategoryDefn --not available in ODS
			--,cov.CoverageCode AS InternalCoverageCode-- ?
			--,cov.CoverageName AS InternalCoverageName--? 
			--,ccl.CoverageClassCode AS StatClassCode
			--,pco.ClassCode AS ISOClassCode
		FROM Typelist.LineOfBusiness lob
		JOIN Typelist.SourceSystem sty ON sty.SourceSystemSK = lob.SourceSystemSK
		--JOIN Typelist.Coverage cov ON cov.SourceSystemSK = lob.SourceSystemSK
		--JOIN Typelist.CoverageClass ccl ON ccl.IsStatCodeInd = 1
		--JOIN Policy.PolicyCoverage pco ON pco.SourceSystemSK = lob.SourceSystemSK 
		WHERE lob.ETLUpdateDateTime > @DateFrom
		
		UNION ALL
		
		SELECT
			--ProductCategorySK AUTO GENERATED
			--RowCreatedBySK		  Populated in ADF
			--,RowCreatedDtm		  Populated in ADF
			--,RowLastUpdatedBySK	  Populated in ADF
			--,RowLastUpdatedDtm	  Populated in ADF
			sty.SourceSystemCode AS SourceSystemCode
			,sub.SublineCode AS SourceCode -- doesn't exist in ODS
			,CAST('1900-01-01' AS DATETIME) AS RowEffectiveFromDatetime
			,CAST('3000-01-01' AS DATETIME) AS RowEffectiveToDatetime
			,0 AS GovernanceValidationInd -- generated by default not loaded from the ODS - Default value '0'
			,0 AS StandardValueInd -- generated by default not loaded from the ODS - Default value '0'
			,'NoStdVal' AS StandardValueCKcode -- System generated by default - Default value '8(NoStdVal)'
			,NULL AS ParentProductCategoryCKcode --not available in ODS '(UnknownInSrc)' ??
			,'C' AS ProductCategoryTypeCKcode									-- ref table ???
			,'INSURSUBTYP' AS ProductCategoryLevelCK -- ref table ???
			,sub.SublineCode AS ProductCategoryCode
			,sub.SublineName AS ProductCategoryName
			,sub.SublineCode AS ProductCategoryFullyQualifiedName --not available in ODS 
			,cast(sub.SublineCode AS VARCHAR(20)) AS ProductCategoryAbrv
			,NULL AS ProductCategoryDefn --not available in ODS
			--,cov.CoverageCode AS InternalCoverageCode-- ?
			--,cov.CoverageName AS InternalCoverageName--? 
			--,ccl.CoverageClassCode AS StatClassCode
			--,pco.ClassCode AS ISOClassCode
		FROM Typelist.Subline sub
		JOIN Typelist.SourceSystem sty ON sty.SourceSystemSK = sub.SourceSystemSK
		--JOIN Typelist.Coverage cov ON cov.SourceSystemSK = lob.SourceSystemSK
		--JOIN Typelist.CoverageClass ccl ON ccl.IsStatCodeInd = 1
		--JOIN Policy.PolicyCoverage pco ON pco.SourceSystemSK = lob.SourceSystemSK 
		WHERE sub.ETLUpdateDateTime > @DateFrom
		
		UNION ALL
		
		SELECT
			--ProductCategorySK AUTO GENERATED
			--RowCreatedBySK		  Populated in ADF
			--,RowCreatedDtm		  Populated in ADF
			--,RowLastUpdatedBySK	  Populated in ADF
			--,RowLastUpdatedDtm	  Populated in ADF
			sty.SourceSystemCode AS SourceSystemCode
			,cov.CoverageCode AS SourceCode										-- doesn't exist in ODS
			,CAST('1900-01-01' AS DATETIME) AS RowEffectiveFromDatetime
			,CAST('3000-01-01' AS DATETIME) AS RowEffectiveToDatetime
			,0 AS GovernanceValidationInd										-- generated by default not loaded from the ODS - Default value '0'
			,0 AS StandardValueInd												-- generated by default not loaded from the ODS - Default value '0'
			,'NoStdVal' AS StandardValueCKcode									-- System generated by default - Default value '8(NoStdVal)'
			,NULL AS ParentProductCategoryCKcode								--not available in ODS '(UnknownInSrc)' ??
			,'C' AS ProductCategoryTypeCKcode									-- ref table ???
			,'PREM&CLMCOVG' AS ProductCategoryLevelCKcode						-- ref table ???
			,cov.CoverageCode AS ProductCategoryCode
			,cov.CoverageName AS ProductCategoryName
			,cov.CoverageCode AS ProductCategoryFullyQualifiedName							--not available in ODS 
			,cast(cov.CoverageCode AS VARCHAR(20)) AS ProductCategoryAbrv
			,NULL AS ProductCategoryDefn										--not available in ODS
			--,cov.CoverageCode AS InternalCoverageCode-- ?
			--,cov.CoverageName AS InternalCoverageName--? 
			--,ccl.CoverageClassCode AS StatClassCode
			--,pco.ClassCode AS ISOClassCode
		FROM Typelist.Coverage cov
		JOIN Typelist.SourceSystem sty ON sty.SourceSystemSK = cov.SourceSystemSK
		--JOIN Typelist.CoverageClass ccl ON ccl.IsStatCodeInd = 1
		--JOIN Policy.PolicyCoverage pco ON pco.SourceSystemSK = cov.SourceSystemSK 
		WHERE cov.ETLUpdateDateTime > @DateFrom
		
		UNION ALL
		
		-- SubCoverage with SubCoverage
		SELECT
			--ProductCategorySK AUTO GENERATED
			--RowCreatedBySK		  Populated in ADF
			--,RowCreatedDtm		  Populated in ADF
			--,RowLastUpdatedBySK	  Populated in ADF
			--,RowLastUpdatedDtm	  Populated in ADF
			sty.SourceSystemCode AS SourceSystemCode
			,sco.SubCoverageCode AS SourceCode -- doesn't exist in ODS
			,CAST('1900-01-01' AS DATETIME) AS RowEffectiveFromDatetime
			,CAST('3000-01-01' AS DATETIME) AS RowEffectiveToDatetime
			,0 AS GovernanceValidationInd -- generated by default not loaded from the ODS - Default value '0'
			,0 AS StandardValueInd -- generated by default not loaded from the ODS - Default value '0'
			,'NoStdVal' AS StandardValueCKcode -- System generated by default - Default value '8(NoStdVal)'
			,NULL AS ParentProductCategoryCKcode --not available in ODS '(UnknownInSrc)' ??
			,'C' AS ProductCategoryTypeCKcode									-- ref table ???
			,'PREM&CLMSUBCOVG' AS ProductCategoryLevelCKcode -- ref table ???
			,sco.SubCoverageCode AS ProductCategoryCode
			,sco.SubCoverageName AS ProductCategoryName
			,sco.SubCoverageCode AS ProductCategoryFullyQualifiedName --not available in ODS 
			,cast(sco.SubCoverageCode AS VARCHAR(20)) AS ProductCategoryAbrv
			,NULL AS ProductCategoryDefn --not available in ODS
			--,sco.SubCoverageCode AS InternalCoverageCode-- ?
			--,sco.SubCoverageName AS InternalCoverageName--? 
			--,ccl.CoverageClassCode AS StatClassCode
			--,pco.ClassCode AS ISOClassCode
		FROM Typelist.SubCoverage sco
		JOIN Typelist.SourceSystem sty ON sty.SourceSystemSK = sco.SourceSystemSK
		--JOIN Typelist.CoverageClass ccl ON ccl.IsStatCodeInd = 1
		--JOIN Policy.PolicyCoverage pco ON pco.SourceSystemSK = sco.SourceSystemSK 
		WHERE sco.ETLUpdateDateTime > @DateFrom
		) AS tmp
	) AS tpl
WHERE tpl.rn = 1
ORDER BY length DESC
GO
