USE [sqldb-ods-dev]
GO
/****** Object:  StoredProcedure [StgADM].[SrcDimPremiumExposureCategory]    Script Date: 28.10.2022 12:27:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [StgADM].[SrcDimPremiumExposureCategory] @CutOffDateFrom VARCHAR(100)
AS
DECLARE @DateFrom DATETIME = cast(@CutOffDateFrom AS DATETIME)

select 

	row.*
FROM (
	SELECT ROW_NUMBER() OVER (
			PARTITION BY 
			tpt.PremiumTypeCode
			,tpt.PremiumTypeName
			,src.SourceSystemSk
			ORDER BY src.SourceSystemCode
				,tpt.PremiumTypeName
			) row_num

,tpt.PremiumTypeCode  AS SourceCode
,src.SourceSystemCode  AS SourceSystemCode
,CAST('1900-01-01' AS DATETIME) AS RowEffectiveFromDatetime
,CAST('3000-01-01' AS DATETIME) AS RowEffectiveToDatetime
,'0' AS GovernanceValidationInd -- generated by default not loaded from the ODS - Default value '0'
,'NoStdVal' AS StandardValueCk -- System generated by default - Default value '8(NoStdVal)'
,'0' AS StandardValueInd -- generated by default not loaded from the ODS - Default value '0'
,tpt.PremiumTypeCode AS PremiumExposureCategoryCode
,tpt.PremiumTypeName AS PremiumExposureCategoryName
,tpt.PremiumTypeCode AS PremiumExposureCategoryAbrv
,null as PremiumExposureCategoryDefn
from TypeList.PremiumType tpt
join typelist.SourceSystem src on src.SourceSystemSK=tpt.SourceSystemSK
	WHERE tpt.ETLUpdateDateTime >  @DateFrom
	) row
WHERE row.row_num = 1
GO
