USE [sqldb-ods-dev]
GO
/****** Object:  StoredProcedure [StgADM].[SrcDimLobClaimFinancialTransactionClass]    Script Date: 28.10.2022 15:06:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [StgADM].[SrcDimLobClaimFinancialTransactionClass] @CutOffDateFrom VARCHAR(100)
AS
DECLARE @DateFrom DATETIME = CAST(@CutOffDateFrom AS DATETIME)

SELECT *
FROM (
	SELECT *
		,ROW_NUMBER() OVER (PARTITION BY SourceSystemSKcode,SourceCode ORDER BY SourceCode) AS rn
	FROM (
		SELECT
			--ProductCategorySK AUTO GENERATED
			--RowCreatedBySK		  Populated in ADF
			--,RowCreatedDtm		  Populated in ADF
			--,RowLastUpdatedBySK	  Populated in ADF
			--,RowLastUpdatedDtm	  Populated in ADF
			src.SourceSystemCode AS SourceSystemSKcode
			,ctct.ClaimTransactionCategoryTypeCode AS SourceCode				-- doesn't exist in ODS
			,TRY_CAST('1900-01-01' AS DATETIME) AS RowEffectiveFromDatetime
			,TRY_CAST('3000-01-01' AS DATETIME) AS RowEffectiveToDatetime
			,'0' AS GovernanceValidationInd										-- generated by default not loaded from the ODS - Default value '0'
			,'0' AS StandardValueInd											-- generated by default not loaded from the ODS - Default value '0'
			,'NoStdVal' AS StandardValueCkCode									-- System generated by default - Default value '8(NoStdVal)'
			,lob.LineofBusinessCode
			,'INSURTYP' AS ProductCategoryLevelLOBCode
			,ctct.ClaimTransactionCategoryTypeCode AS LobClaimFinancialTransactionClassCode
			,ctct.ClaimTransactionCategoryTypeName AS LobClaimFinancialTransactionClassName
			,ctct.ClaimTransactionCategoryTypeCode AS LobClaimFinancialTransactionClassAbrv
				,NULL AS LobClaimFinancialTransactionClassDefn
		FROM Claim.Claim clm
		JOIN Typelist.SourceSystem src ON src.SourceSystemSK = clm.SourceSystemSK
		LEFT JOIN Claim.ClaimPolicyAssociation cpa ON cpa.ClaimSK = clm.ClaimSK
		LEFT JOIN Claim.ClaimPolicy clp ON clp.ClaimPolicySK = cpa.ClaimPolicySK
		LEFT JOIN Typelist.LineOfBusiness lob ON lob.LineofBusinessSK = clp.LineofBusinessSK
		LEFT JOIN Finance.ClaimTransaction clt ON clt.ClaimSK = clm.ClaimSK
		LEFT JOIN Typelist.ClaimTransactionCategoryType ctct ON ctct.ClaimTransactionCategoryTypeSK = clt.ClaimTransactionCategoryTypeSK
		WHERE clm.ETLUpdateDateTime > @DateFrom
		) tmp
	) tbl
	WHERE tbl.rn = 1
GO
