USE [sqldb-ods-dev]
GO
/****** Object:  StoredProcedure [StgADM].[SrcDimLobClaimCategory]    Script Date: 28.10.2022 12:27:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [StgADM].[SrcDimLobClaimCategory] @CutOffDateFrom VARCHAR(100)
AS
DECLARE @DateFrom DATETIME = CAST(@CutOffDateFrom AS DATETIME)

SELECT * FROM 
(
	SELECT *
		, ROW_NUMBER() OVER (PARTITION BY SourceSystemSKcode, SourceCode ORDER BY SourceCode) AS rn
	FROM 
		(
		SELECT 
			--ProductCategorySK			AUTO GENERATED
			--RowCreatedBySK		  Populated in ADF
			--,RowCreatedDtm		  Populated in ADF
			--,RowLastUpdatedBySK	  Populated in ADF
			--,RowLastUpdatedDtm	  Populated in ADF
			src.SourceSystemCode AS SourceSystemSKcode
			,cct.ClaimCategoryTypeCode AS SourceCode	-- doesn't exist in ODS
			,TRY_CAST('1900-01-01' AS DATETIME) AS RowEffectiveFromDatetime
			,TRY_CAST('3000-01-01' AS DATETIME) AS RowEffectiveToDatetime
			,'0' AS GovernanceValidationInd				-- generated by default not loaded from the ODS - Default value '0'
			,'0' AS StandardValueInd					-- generated by default not loaded from the ODS - Default value '0'
			,'NoStdVal' AS StandardValueCKCode			-- System generated by default - Default value '8(NoStdVal)'
			,lob.LineofBusinessCode
			,'INSURTYP' AS ProductCategoryLevelLOBCode
			,CAST(lob.LineofBusinessCode AS VARCHAR(20)) AS LineOfBusinessAbrv
			,cct.ClaimCategoryTypeCode AS ClaimCategoryCode
			,cct.ClaimCategoryTypeName AS ClaimCategoryName
			,cct.ClaimCategoryTypeCode AS ClaimCategoryAbrv
			,NULL AS ClaimCategoryDefn
		FROM Typelist.ClaimCategoryType cct
		JOIN Typelist.SourceSystem src ON src.SourceSystemSK = cct.SourceSystemSK
		LEFT JOIN Claim.Claim clm ON cct.ClaimCategoryTypeSK = clm.ClaimCategoryTypeSK
		LEFT JOIN Claim.ClaimPolicyAssociation cpa ON cpa.ClaimSK = clm.ClaimSK
		LEFT JOIN Claim.ClaimPolicy clp ON clp.ClaimPolicySK = cpa.ClaimPolicySK
		LEFT JOIN Typelist.LineOfBusiness lob ON lob.LineofBusinessSK = clp.LineofBusinessSK
		WHERE clm.ETLUpdateDateTime > @DateFrom 

	) tbl
) tbb
WHERE tbb.rn = 1
GO
