USE [sqldb-ods-dev]
GO
/****** Object:  StoredProcedure [StgADM].[SrcDIMClaimFilingType]    Script Date: 28.10.2022 11:11:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [StgADM].[SrcDIMClaimFilingType] @CutOffDateFrom VARCHAR(100)
AS
DECLARE @DateFrom DATETIME = cast(@CutOffDateFrom AS DATETIME)

SELECT row.*
FROM (
	SELECT ROW_NUMBER() OVER (
			PARTITION BY src.SourceSystemCode
			,tct.CoverageTriggerCode
			,tct.CoverageTriggerName
			,src.SourceSystemSk ORDER BY src.SourceSystemCode
				,tct.CoverageTriggerName
			) row_num
		,src.SourceSystemCode AS SourceSystemCode
		,tct.CoverageTriggerCode AS SourceCode -- doesn't exist in ODS
		,CAST('1900-01-01' AS DATETIME) AS RowEffectiveFromDatetime
		,CAST('3000-01-01' AS DATETIME) AS RowEffectiveToDatetime
		,'0' AS GovernanceValidationInd -- generated by default not loaded from the ODS - Default value '0'
		,'NoStdVal' AS StandardValueCk -- System generated by default - Default value '8(NoStdVal)'
		,'0' AS StandardValueInd -- generated by default not loaded from the ODS - Default value '0'
		,tct.CoverageTriggerCode AS [ClaimFilingTypeCode]
		,tct.CoverageTriggerName AS [ClaimFilingTypeName]
		,tct.CoverageTriggerCode AS [ClaimFilingTypeAbrv]
		,NULL AS ClaimFilingTypeDefn ---- generated by default not loaded from the ODS - Default value null
	FROM Typelist.CoverageTrigger tct
	JOIN Typelist.SourceSystem src ON tct.SourceSystemSK = src.SourceSystemSK
	WHERE tct.ETLUpdateDateTime > @DateFrom
	) row
WHERE row.row_num = 1
GO
