USE [sqldb-ods-dev]
GO
/****** Object:  Table [StgPolicy].[SrcPolicyTrans]    Script Date: 28.10.2022 12:27:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [StgPolicy].[SrcPolicyTrans](
	[SourceSystemCode] [nvarchar](255) NULL,
	[SourceCode] [nvarchar](255) NULL,
	[ProcessDateTime] [datetime] NULL,
	[IsCurrentInd] [int] NOT NULL,
	[PolicySourceCode] [nvarchar](255) NULL,
	[PolicyNum] [nvarchar](255) NULL,
	[TermNum] [nvarchar](255) NULL,
	[PolicyTransNum] [nvarchar](255) NULL,
	[PolicyTransVersionNum] [int] NULL,
	[PolicyTransTypeCode] [nvarchar](255) NULL,
	[PolicyTransTypeDesc] [nvarchar](255) NULL,
	[TransStartDatetime] [datetime] NULL,
	[TransEndDatetime] [datetime] NULL,
	[PolicyTransStatusCode] [nvarchar](255) NULL,
	[PolicyTransStatusDesc] [nvarchar](255) NULL,
	[UnderwritingStatusCode] [nvarchar](255) NULL,
	[UnderwritingStatusDesc] [nvarchar](255) NULL,
	[RegistrationDate] [datetime] NULL,
	[PolicyIssuanceDate] [datetime] NULL,
	[PolicyCancellationDate] [datetime] NULL,
	[NextRenewalCheckDate] [datetime] NULL,
	[RetroActiveDate] [datetime] NULL,
	[BusinessUnitCode] [nvarchar](255) NULL,
	[BusinessUnitDesc] [nvarchar](255) NULL,
	[PolicyEffectiveDate] [datetime] NULL,
	[LegacyPolicyNum] [nvarchar](255) NULL,
	[PolicyExpirationDate] [datetime] NULL,
	[IsTransportationPolicyInd] [int] NULL,
	[StandardIndustryCode] [nvarchar](255) NULL,
	[StandardIndustryCodeDesc] [nvarchar](255) NULL,
	[NorthAmericanIndustryClassificationCode] [nvarchar](255) NULL,
	[NorthAmericanIndustryClassificationDesc] [nvarchar](255) NULL,
	[IsPremWaivedInd] [int] NULL,
	[BaseCurrencyCode] [nvarchar](255) NULL,
	[BaseCurrencyDesc] [nvarchar](255) NULL,
	[OriginalCurrencyCode] [nvarchar](255) NULL,
	[OriginalCurrencyDesc] [nvarchar](255) NULL,
	[ReportingCurrencyCode] [nvarchar](255) NULL,
	[ReportingCurrencyDesc] [nvarchar](255) NULL,
	[EstWrittenPremiumBaseAmt] [decimal](20, 6) NULL,
	[EstWrittenPremiumOriginalAmt] [decimal](20, 6) NULL,
	[EstWrittenPremiumReportingAmt] [decimal](20, 6) NULL,
	[TermPremiumBaseAmt] [decimal](20, 6) NULL,
	[TermPremiumOriginalAmt] [decimal](20, 6) NULL,
	[TermPremiumReportingAmt] [decimal](20, 6) NULL,
	[AddlRetPremiumBaseAmt] [decimal](20, 6) NULL,
	[AddlRetPremiumOriginalAmt] [decimal](20, 6) NULL,
	[AddlRetPremiumReportingAmt] [decimal](20, 6) NULL,
	[OOSOffsetPremiumBaseAmt] [decimal](20, 6) NULL,
	[OOSOffsetPremiumOriginalAmt] [decimal](20, 6) NULL,
	[OOSOffsetPremiumReportingAmt] [decimal](20, 6) NULL,
	[OOSFuturePremiumBaseAmt] [decimal](20, 6) NULL,
	[OOSFuturePremiumOriginalAmt] [decimal](20, 6) NULL,
	[OOSFuturePremiumReportingAmt] [decimal](20, 6) NULL,
	[OOSTypeCode] [nvarchar](255) NULL,
	[OOSTypeDesc] [nvarchar](255) NULL,
	[UltimateLossRatioPct] [decimal](20, 6) NULL,
	[RevisedUltimateLossRatioPct] [decimal](20, 6) NULL,
	[PercentOfTechnicalPricePct] [decimal](20, 6) NULL,
	[PremiumChangePct] [decimal](20, 6) NULL,
	[DeductionsAttachmentsChangePct] [decimal](20, 6) NULL,
	[CoverageChangePct] [decimal](20, 6) NULL,
	[ExposureChangePct] [decimal](20, 6) NULL,
	[IsRenewalPriceIndexDataInd] [int] NULL,
	[RenewalPriceIndexPct] [decimal](20, 6) NULL,
	[IsPolicyEffectiveDateProposedInd] [int] NULL,
	[IsPolicyExpirationDateProposedInd] [int] NULL,
	[IsProjectPolicyInd] [int] NULL,
	[IsFacReinsurancePurchasedInd] [int] NULL,
	[ProjectName] [nvarchar](255) NULL,
	[ProjectTypeCode] [nvarchar](255) NULL,
	[ProjectTypeDesc] [nvarchar](255) NULL,
	[ISOClassCode] [nvarchar](255) NULL,
	[IsNYFreeTradeZoneInd] [int] NULL,
	[NYFreeTradeZoneClassCode] [nvarchar](255) NULL,
	[IsPolicyTrackAsNonRecurringPremiumInd] [int] NULL,
	[IsMiddleMarketPolicyInd] [int] NULL,
	[BusinessTypeCode] [nvarchar](255) NULL,
	[BusinessTypeDesc] [nvarchar](255) NULL,
	[WritingCompanySourceCode] [nvarchar](255) NULL,
	[IsRunoffERPInd] [int] NULL,
	[RunoffERPDate] [datetime] NULL,
	[IsFirmOrderNotedInd] [int] NULL,
	[WrittenLinePct] [decimal](20, 6) NULL,
	[SignedLinePct] [decimal](20, 6) NULL,
	[PremiumAllocationPct] [decimal](20, 6) NULL,
	[CoverageTriggerCode] [nvarchar](255) NULL,
	[CoverageTriggerDesc] [nvarchar](255) NULL,
	[ProfessionCode] [nvarchar](255) NULL,
	[ProfessionDesc] [nvarchar](255) NULL,
	[DomicileCountryCode] [nvarchar](255) NULL,
	[DomicileCountryDesc] [nvarchar](255) NULL,
	[DomicileStateCode] [nvarchar](255) NULL,
	[DomicileStateDesc] [nvarchar](255) NULL,
	[MinimumEarnedPremiumPct] [decimal](20, 6) NULL,
	[TreatyOrReferralAppliesDesc] [nvarchar](255) NULL,
	[DaysNoticeOfCancellationNum] [int] NULL,
	[IsFacultativeEquipmentBreakdownInd] [int] NULL,
	[IsEquipmentBreakdownPremiumIncludedInd] [int] NULL,
	[IsComboPolicyInd] [int] NULL,
	[IsAdmittedDeregInd] [int] NULL,
	[QuotaShareAppliesInd] [int] NULL,
	[IsSharedLimitInd] [int] NULL,
	[PendingAndPriorLitigationDate] [datetime] NULL,
	[IsPremiumAuditableInd] [int] NULL,
	[IsTRIAOfferedInd] [int] NULL,
	[IsFortune500CompanyInd] [int] NULL,
	[ClassofBusinessCode] [nvarchar](255) NULL,
	[IsBureauInd] [int] NULL,
	[IsDeclarationPremBearingInd] [int] NULL,
	[IsRiskBordereauProvidedInd] [int] NULL,
	[IsClaimBordereauProvidedInd] [int] NULL,
	[IsPaidPremiumBordereauProvidedInd] [int] NULL,
	[IsFrontedInd] [int] NULL,
	[IsCombinedPackageInd] [int] NULL,
	[IsPremiumWaivedInd] [int] NULL,
	[FileName] [nvarchar](500) NULL,
	[FilePath] [nvarchar](500) NULL,
	[IsValidInd] [tinyint] NULL
) ON [PRIMARY]
GO
