USE [sqldb-ods-dev]
GO
/****** Object:  StoredProcedure [StgPolicy].[LoadPolicyTrans]    Script Date: 28.10.2022 12:27:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   procedure [StgPolicy].[LoadPolicyTrans] @pBatchId int
as

INSERT INTO Policy.PolicyTrans
	(ETLCreateDateTime
    ,ETLUpdateDateTime
    ,ETLCreateProcessNum
    ,ETLUpdateProcessNum
    ,SourceSystemSK
    ,SourceCode
    ,ProcessDateTime
    ,IsCurrentInd
    ,PolicySK
    ,PolicyNum
    ,TermNum
    ,PolicyTransNum
    ,PolicyTransVersionNum
    ,PolicyTransTypeSK
    ,TransStartDatetime
    ,TransEndDatetime
    ,PolicyTransStatusSK
    ,UnderwritingStatusSK
    ,RegistrationDate
    ,PolicyIssuanceDate
    ,PolicyCancellationDate
    ,NextRenewalCheckDate
    ,RetroActiveDate
    ,BusinessUnitSK
    ,PolicyEffectiveDate
    ,LegacyPolicyNum
    ,PolicyExpirationDate
    ,IsTransportationPolicyInd
    ,StandardIndustryCodeSK
    ,NorthAmericanIndustryClassificationSK
    ,IsPremiumWaivedInd
    ,BaseCurrencySK
    ,OriginalCurrencySK
    ,ReportingCurrencySK
    ,EstWrittenPremiumBaseAmt
    ,EstWrittenPremiumOriginalAmt
    ,EstWrittenPremiumReportingAmt
    ,TermPremiumBaseAmt
    ,TermPremiumOriginalAmt
    ,TermPremiumReportingAmt
    ,AddlRetPremiumBaseAmt
    ,AddlRetPremiumOriginalAmt
    ,AddlRetPremiumReportingAmt
    ,OOSOffsetPremiumBaseAmt
    ,OOSOffsetPremiumOriginalAmt
    ,OOSOffsetPremiumReportingAmt
    ,OOSFuturePremiumBaseAmt
    ,OOSFuturePremiumOriginalAmt
    ,OOSFuturePremiumReportingAmt
    ,OOSTypeCode
    ,OOSTypeDesc
    ,UltimateLossRatioPct
    ,RevisedUltimateLossRatioPct
    ,PercentOfTechnicalPricePct
    ,PremiumChangePct
    ,DeductionsAttachmentsChangePct
    ,CoverageChangePct
    ,ExposureChangePct
    ,IsRenewalPriceIndexDataInd
    ,RenewalPriceIndexPct
    ,IsPolicyEffectiveDateProposedInd
    ,IsPolicyExpirationDateProposedInd
    ,IsProjectPolicyInd
    ,IsFacReinsurancePurchasedInd
    ,ProjectName
    ,ProjectTypeSK
    ,ISOClassCode
    ,IsNYFreeTradeZoneInd
    ,NYFreeTradeZoneClassCode
    ,IsPolicyTrackAsNonRecurringPremiumInd
    ,IsMiddleMarketPolicyInd
    ,BusinessTypeSK
    ,WritingCompanySK
    ,IsRunoffERPInd
    ,RunoffERPDate
    ,IsFirmOrderNotedInd
    ,WrittenLinePct
    ,SignedLinePct
    ,PremiumAllocationPct
    ,CoverageTriggerSK
    ,ProfessionSK
    ,DomicileCountrySK
    ,DomicileStateSK
    ,MinimumEarnedPremiumPct
    ,TreatyOrReferralAppliesDesc
    ,DaysNoticeOfCancellationNum
    ,IsFacultativeEquipmentBreakdownInd
    ,IsEquipmentBreakdownPremiumIncludedInd
    ,IsComboPolicyInd
    ,IsAdmittedDeregInd
    ,QuotaShareAppliesInd
    ,IsSharedLimitInd
    ,PendingAndPriorLitigationDate
    ,IsPremiumAuditableInd
    ,IsTRIAOfferedInd
    ,IsFortune500CompanyInd
    ,ClassofBusinessCode
    ,IsBureauInd
    ,IsDeclarationPremBearingInd
    ,IsRiskBordereauProvidedInd
    ,IsClaimBordereauProvidedInd
    ,IsPaidPremiumBordereauProvidedInd
    ,IsFrontedInd
    ,IsCombinedPackageInd)
SELECT getdate() as ETLCreateDateTime
	,getdate() as ETLUpdateDateTime
	,@pBatchId as ETLCreateProcessNum
	,@pBatchId as ETLUpdateProcessNum
	,SourceSystemSK
	,SourceCode
	,ProcessDateTime
	,IsCurrentInd
	,PolicySK
	,PolicyNum
	,TermNum
	,PolicyTransNum
	,PolicyTransVersionNum
	,PolicyTransTypeSK
	,TransStartDatetime
	,TransEndDatetime
	,PolicyTransStatusSK
	,UnderwritingStatusSK
	,RegistrationDate
	,PolicyIssuanceDate
	,PolicyCancellationDate
	,NextRenewalCheckDate
	,RetroActiveDate
	,BusinessUnitSK
	,PolicyEffectiveDate
	,LegacyPolicyNum
	,PolicyExpirationDate
	,IsTransportationPolicyInd
	,StandardIndustryCodeSK
	,NorthAmericanIndustryClassificationSK
	,IsPremiumWaivedInd
	,BaseCurrencySK
	,OriginalCurrencySK
	,ReportingCurrencySK
	,EstWrittenPremiumBaseAmt
	,EstWrittenPremiumOriginalAmt
	,EstWrittenPremiumReportingAmt
	,TermPremiumBaseAmt
	,TermPremiumOriginalAmt
	,TermPremiumReportingAmt
	,AddlRetPremiumBaseAmt
	,AddlRetPremiumOriginalAmt
	,AddlRetPremiumReportingAmt
	,OOSOffsetPremiumBaseAmt
	,OOSOffsetPremiumOriginalAmt
	,OOSOffsetPremiumReportingAmt
	,OOSFuturePremiumBaseAmt
	,OOSFuturePremiumOriginalAmt
	,OOSFuturePremiumReportingAmt
	,OOSTypeCode
	,OOSTypeDesc
	,UltimateLossRatioPct
	,RevisedUltimateLossRatioPct
	,PercentOfTechnicalPricePct
	,PremiumChangePct
	,DeductionsAttachmentsChangePct
	,CoverageChangePct
	,ExposureChangePct
	,IsRenewalPriceIndexDataInd
	,RenewalPriceIndexPct
	,IsPolicyEffectiveDateProposedInd
	,IsPolicyExpirationDateProposedInd
	,IsProjectPolicyInd
	,IsFacReinsurancePurchasedInd
	,ProjectName
	,ProjectTypeSK
	,ISOClassCode
	,IsNYFreeTradeZoneInd
	,NYFreeTradeZoneClassCode
	,IsPolicyTrackAsNonRecurringPremiumInd
	,IsMiddleMarketPolicyInd
	,BusinessTypeSK
	,WritingCompanySK
	,IsRunoffERPInd
	,RunoffERPDate
	,IsFirmOrderNotedInd
	,WrittenLinePct
	,SignedLinePct
	,PremiumAllocationPct
	,CoverageTriggerSK
	,ProfessionSK
	,DomicileCountrySK
	,DomicileStateSK
	,MinimumEarnedPremiumPct
	,TreatyOrReferralAppliesDesc
	,DaysNoticeOfCancellationNum
	,IsFacultativeEquipmentBreakdownInd
	,IsEquipmentBreakdownPremiumIncludedInd
	,IsComboPolicyInd
	,IsAdmittedDeregInd
	,QuotaShareAppliesInd
	,IsSharedLimitInd
	,PendingAndPriorLitigationDate
	,IsPremiumAuditableInd
	,IsTRIAOfferedInd
	,IsFortune500CompanyInd
	,ClassofBusinessCode
	,IsBureauInd
	,IsDeclarationPremBearingInd
	,IsRiskBordereauProvidedInd
	,IsClaimBordereauProvidedInd
	,IsPaidPremiumBordereauProvidedInd
	,IsFrontedInd
	,IsCombinedPackageInd
FROM StgPolicy.StgPolicyTrans
GO
